public with sharing class ProjectTaskTriggerHandler {
    public static void handleAfterInsert(List<Project_Task__c> newProjectTasks, Map<Id, Project_Task__c> newProjectTasksMap) {
        
    }

    public static void handleAfterInsert(List<Project_Task__c> newProjectTasks, Map<Id, Project_Task__c> newProjectTasksMap, List<Project_Task__c> oldProjectTasks, Map<Id, Project_Task__c> oldProjectTasksMap) {
        
    }
}